Interactive-list
emmanuellekamwa/Todo-list pull request #3
Opened 2021-08-20 18:01 UTC by emmanuellekamwa

In this project, I have:
- Created a new javascript file that contains methods related to the status update
- Added event listener to checkbox
- Updated items object's value for completed key upon user actions
- Stored the updated array in local storage

2021-08-20 21:21 UTC, Lameck1 requested changes
Hi @emmanuellekamwa, 

Good job so far!
Let's work on some issues that are still hampering our moving forward though.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-20 21:21 UTC, Lameck1 commented on src/index.js
> +    renderList();
![no-test-data](https://user-images.githubusercontent.com/45002654/130292414-7f7d99ca-2f20-4f06-a539-06b328aff051.PNG)


- [ ] As suggests in the screenshot above, this function is checking storage, yes, but not rendering the todo list. Let see why:
    - When loading the app, ideally the `localStorage` is still blank. But then, we are setting the `list` to `listData` which is a reference to a `currently dataless localStorage`.

# Suggestion

I think we need to set some data to` localStorage` first, something like this work for me when testing your app locally:

```JavaScript
function checkStorage() {
  if (!localStorage.getItem('list')) {
    localStorage.setItem('list', JSON.stringify(list));
  }
}

window.onload = () => {
  checkStorage();
  renderList();
};
```

## Note
When the app can't render tasks, there is really no way to properly test it for this milestone.

2021-08-20 21:21 UTC, Lameck1 commented on src/index.js
> +    });
- [ ] The correct `eventListener` for this checkbox is `'change'` as per requirement. A `'click'` event also works but for this task it is preferably a `'change'` event.
- [ ] From my test, calling `renderList()` method inside this `eventListener` is buggy. Where is the problem? You are trying to do a recursive call to this method(calling `renderList()` within itself inside this `eventListener`). I suggest you refactor this` eventListener` outside of `renderList()` method.

2021-08-21 06:27 UTC, bellom approved these changes
## Hi @emmanuellekamwa 👏  

**Great work making all the necessary corrections from the previous review.**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-21 06:30 UTC, merged